/********************************************/
/*  author: Mohamed Walid               	*/
/*  version: V03                            */
/*  Date: 18 NOV 2023	   					*/
/*  SWC : TIM2                   			*/
/********************************************/

#ifndef		TIM2_CONFIG_H
#define 	TIM2_CONFIG_H

#define		CPU_FREQ_IN_KHZ			8000



/* you can choose between:-
 *
 *	 TIM2_NORMAL_MODE
 *	 TIM2_CTC_MODE
 *	 TIM2_FAST_PWM_MODE
 *	 TIM2_PHASE_CORRECT_PWM_MODE
 *
 */


#define 	TIM2_MODE 		TIM2_CTC_MODE



#if 	TIM2_MODE == TIM2_FAST_PWM_MODE || TIM2_MODE == TIM2_PHASE_CORRECT_PWM_MODE

/*
 * Options :
 * 		TIM2_PWM_INVERTED
 * 		TIM2_PWM_NON_INVERTED
 *
 */

#define 	TIM2_PWM_MODE	TIM2_PWM_NON_INVERTED


#else

/* options :
 * 			TIM2_ASYNCH_FUNC_USED
 *          TIM2_ASYNCH_FUNC_NOT_USED
 *
 */


#define     TIM2_ASYNCH_FUNC_USE_STATE      TIM2_ASYNCH_FUNC_NOT_USED


#endif




/* you can choose between:-
 *
 *  TIM2_PRESCALER_CLK_BY_1
 *  TIM2_PRESCALER_CLK_BY_8
 *  TIM2_PRESCALER_CLK_BY_32
 *  TIM2_PRESCALER_CLK_BY_64
 *  TIM2_PRESCALER_CLK_BY_128
 *  TIM2_PRESCALER_CLK_BY_256
 *  TIM2_PRESCALER_CLK_BY_1024
 */


#define 	TIM2_PRESCALER_CHOICE		TIM2_PRESCALER_CLK_BY_32


#if	TIM2_PRESCALER_CHOICE==TIM2_PRESCALER_CLK_BY_1

#define	TIM2_TICK_TIME_INVERSE	CPU_FREQ_IN_KHZ/TIM2_CLK_PRESCALER_1

#elif TIM2_PRESCALER_CHOICE==TIM2_PRESCALER_CLK_BY_8

#define	TIM2_TICK_TIME_INVERSE	CPU_FREQ_IN_KHZ/TIM2_CLK_PRESCALER_8

#elif TIM2_PRESCALER_CHOICE==TIM2_PRESCALER_CLK_BY_32

#define	TIM2_TICK_TIME_INVERSE	CPU_FREQ_IN_KHZ/TIM2_CLK_PRESCALER_32

#elif TIM2_PRESCALER_CHOICE==TIM2_PRESCALER_CLK_BY_64

#define	TIM2_TICK_TIME_INVERSE	CPU_FREQ_IN_KHZ/TIM2_CLK_PRESCALER_64

#elif TIM2_PRESCALER_CHOICE==TIM2_PRESCALER_CLK_BY_128

#define	TIM2_TICK_TIME_INVERSE	CPU_FREQ_IN_KHZ/TIM2_CLK_PRESCALER_128

#elif TIM2_PRESCALER_CHOICE==TIM2_PRESCALER_CLK_BY_256

#define	TIM2_TICK_TIME_INVERSE	CPU_FREQ_IN_KHZ/TIM2_CLK_PRESCALER_256

#elif TIM2_PRESCALER_CHOICE==TIM2_PRESCALER_CLK_BY_1024

#define	TIM2_TICK_TIME_INVERSE	CPU_FREQ_IN_KHZ/TIM2_CLK_PRESCALER_1024


#endif




#endif
